#!/usr/bin/env python3
"""
build_theme_engine.py
─────────────────────
Packages wallpaper_engine2.py + libmpv-2.dll into a single
standalone  ThemeEngine.exe  using PyInstaller.

Usage (run this script once, from the folder that contains
wallpaper_engine2.py and libmpv-2.dll):

    python build_theme_engine.py

Output:
    dist/ThemeEngine.exe   ← ship this one file

Requirements (auto-installed if missing):
    pyinstaller
    pyinstaller-hooks-contrib
"""

import sys, os, subprocess, shutil, textwrap
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
APP_NAME    = "ThemeEngine"
SCRIPT_NAME = "Theme_engine2.py"
DLL_NAME    = "libmpv-2.dll"          # must sit next to this build script
ICON_FILE   = None                    # set to "theme_engine.ico" if you have one
# ─────────────────────────────────────────────────────────────────────────────

HERE = Path(__file__).parent.resolve()

def info(msg):  print(f"[Build] {msg}")
def die(msg):   print(f"[Build] ERROR: {msg}"); sys.exit(1)


# ── 1. Sanity checks ──────────────────────────────────────────────────────────
script_path = HERE / SCRIPT_NAME
if not script_path.exists():
    die(f"{SCRIPT_NAME} not found in {HERE}\n"
        f"       Place this build script in the same folder as {SCRIPT_NAME}.")

dll_path = HERE / DLL_NAME
if not dll_path.exists():
    die(f"{DLL_NAME} not found in {HERE}\n"
        f"       Copy libmpv-2.dll from your working install into this folder first.")

info(f"Source script : {script_path}")
info(f"mpv DLL       : {dll_path}  ({dll_path.stat().st_size:,} bytes)")


# ── 2. Install PyInstaller if missing ─────────────────────────────────────────
def pip_install(pkg):
    info(f"Installing {pkg} via pip…")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", pkg, "-q"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        die(f"pip install {pkg} failed:\n{result.stderr}")

try:
    import PyInstaller
    info(f"PyInstaller {PyInstaller.__version__} already installed")
except ImportError:
    pip_install("pyinstaller")
    pip_install("pyinstaller-hooks-contrib")

# Install all app dependencies so PyInstaller can find and bundle them.
# pip install is idempotent — already-installed packages finish in < 1 s.
# We do NOT import them here because importing python-mpv immediately tries
# to load libmpv-2.dll via ctypes, which fails unless the DLL folder is
# already on PATH (it isn't when the build script is freshly invoked).
APP_DEPS = [
    "PyQt5",
    "numpy",
    "opencv-python",
    "python-mpv",
    "sounddevice",
    "pyaudiowpatch",
]
info("Ensuring app dependencies are installed…")
for dep in APP_DEPS:
    info(f"  pip install {dep}")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", dep, "-q"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        die(f"pip install {dep} failed:\n{result.stderr}")

# Add the DLL folder to PATH so python-mpv can be imported by PyInstaller's
# analysis phase without raising a FileNotFoundError on libmpv-2.dll
os.environ["PATH"] = str(HERE) + os.pathsep + os.environ.get("PATH", "")
info(f"Added {HERE} to PATH for PyInstaller analysis")


# ── 3. Write the .spec file ───────────────────────────────────────────────────
# We use a spec file for precise control over:
#   - which DLL gets bundled (libmpv-2.dll next to the exe, NOT inside the zip)
#   - PyQt5 platform plugins
#   - hidden imports for cv2, sounddevice, numpy
#   - no console window (windowed=True)

spec_content = textwrap.dedent(f"""\
    # -*- mode: python ; coding: utf-8 -*-
    # Auto-generated by build_theme_engine.py — do not edit by hand

    import sys
    from pathlib import Path
    from PyInstaller.utils.hooks import collect_data_files
    HERE = Path(SPEC).parent   # directory containing the .spec file

    block_cipher = None

    a = Analysis(
        [str(HERE / "{SCRIPT_NAME}")],
        pathex=[str(HERE)],
        binaries=[
            # libmpv-2.dll placed next to the exe (not inside the archive)
            # so Windows can load it normally via PATH/folder lookup
            (str(HERE / "{DLL_NAME}"), "."),
        ],
        hiddenimports=[
            # python-mpv
            "mpv",
            # OpenCV
            "cv2", "cv2.cv2",
            # sounddevice / PortAudio
            "sounddevice", "_sounddevice_data",
            # numpy internals
            "numpy.core._methods",
            "numpy.lib.format",
            # PyQt5 modules used by the app
            "PyQt5.QtWidgets",
            "PyQt5.QtCore",
            "PyQt5.QtGui",
            "PyQt5.sip",
            # tkinter — used by the first-run setup progress window
            # Must be listed explicitly; PyInstaller does not auto-detect it
            "tkinter",
            "tkinter.ttk",
            "tkinter.messagebox",
            "_tkinter",
            # pyaudiowpatch — WASAPI loopback audio
            "pyaudiowpatch",
            "_portaudio",
        ],
        # tkinter needs its Tcl/Tk support files (.tcl scripts, DLLs)
        # collect_data_files finds them from the Python install automatically
        datas=collect_data_files("tkinter"),
        hookspath=[],
        hooksconfig={{}},
        runtime_hooks=[],
        excludes=[
            # Trim unused heavy modules to keep exe smaller
            "matplotlib", "scipy", "PIL",
            "unittest", "email", "html", "http", "xml",
            "xmlrpc", "pydoc", "doctest", "difflib",
        ],
        win_no_prefer_redirects=False,
        win_private_assemblies=False,
        cipher=block_cipher,
        noarchive=False,
    )

    # Keep only essential PyQt5 platform plugins
    a.binaries = [x for x in a.binaries
                  if not (x[0].startswith("PyQt5/Qt5/plugins/") and
                          "platforms" not in x[0] and
                          "imageformats" not in x[0])]

    pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

    exe = EXE(
        pyz, a.scripts, a.binaries, a.zipfiles, a.datas,
        [],
        name="{APP_NAME}",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,           # compress if UPX is on PATH; silently skipped if not
        upx_exclude=["vcruntime140.dll", "python*.dll", "{DLL_NAME}"],
        runtime_tmpdir=None,
        console=False,      # no black console window
        disable_windowed_traceback=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        {"icon=str(HERE / ICON_FILE)," if ICON_FILE else "# icon= (set ICON_FILE in build script to add one)"}
        version_info=None,
    )
""")

spec_path = HERE / f"{APP_NAME}.spec"
spec_path.write_text(spec_content, encoding="utf-8")
info(f"Spec file written: {spec_path}")


# ── 4. Clean previous build artefacts ────────────────────────────────────────
for d in ("build", "dist"):
    target = HERE / d
    if target.exists():
        info(f"Removing old {d}/")
        try:
            shutil.rmtree(target)
        except PermissionError:
            # The old exe is still running or locked by Windows/antivirus.
            exe = target / f"{APP_NAME}.exe"
            print()
            print(f"  ERROR: Cannot delete {target}")
            print(f"  '{exe.name}' is still running or locked.")
            print(f"  Close ThemeEngine.exe (check the system tray too),")
            print(f"  then run this build script again.")
            print()
            sys.exit(1)


# ── 5. Run PyInstaller ────────────────────────────────────────────────────────
info("Running PyInstaller…")
cmd = [
    sys.executable, "-m", "PyInstaller",
    "--clean",
    "--noconfirm",
    str(spec_path),
]
result = subprocess.run(cmd, cwd=str(HERE))
if result.returncode != 0:
    die("PyInstaller failed. Check the output above for details.")


# ── 6. Verify output ──────────────────────────────────────────────────────────
exe_path = HERE / "dist" / f"{APP_NAME}.exe"
if not exe_path.exists():
    die(f"Expected output not found: {exe_path}")

size_mb = exe_path.stat().st_size / 1_048_576
info("=" * 60)
info(f"SUCCESS")
info(f"  Output : {exe_path}")
info(f"  Size   : {size_mb:.1f} MB")
info("=" * 60)
info("Ship this single file — no Python, no DLLs, no install needed.")
info("On the target PC it will:")
info("  • Check Python packages on first run (pip-less — all bundled)")
info("  • Load libmpv-2.dll from the bundled copy")
info("  • Launch the Theme Engine UI directly")


# ── 7. Optional: clean up build/ and .spec ───────────────────────────────────
cleanup = input("\nRemove build/ and .spec file? [Y/n]: ").strip().lower()
if cleanup != "n":
    shutil.rmtree(HERE / "build", ignore_errors=True)
    spec_path.unlink(missing_ok=True)
    info("Cleaned up build artefacts.")
